In [1]:
import numpy as np
import pandas as pd

In [4]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

In [15]:
index = pd.date_range('1/1/2000', periods=8)

8

In [16]:
df = pd.DataFrame(np.random.randn(index.shape[0], 3), index=index,
   ...:                   columns=['A', 'B', 'C'])
   ...: 

In [17]:
df

A         B         C
2000-01-01 -0.196995 -0.003352  0.444708
2000-01-02 -2.541531 -0.782247 -0.064333
2000-01-03  0.173113 -0.279730  1.465295
2000-01-04 -1.006320  0.893319  0.522331
2000-01-05 -0.255289  0.740723 -0.402440
2000-01-06 -1.917776 -0.406347  0.660013
2000-01-07  0.706273  0.703421 -1.135751
2000-01-08 -2.532381 -0.334399 -0.203312

In [18]:
long_series = pd.Series(np.random.randn(1000))

In [19]:
long_series.head()

0   -0.251423
1   -0.871323
2   -0.803107
3   -1.255013
4    0.626270
dtype: float64

In [20]:
long_series.tail()

995    1.372697
996    0.438326
997    2.236752
998    0.787779
999    1.030773
dtype: float64

In [27]:
df[:2]

A         B         C
2000-01-01 -0.196995 -0.003352  0.444708
2000-01-02 -2.541531 -0.782247 -0.064333

In [28]:
df.columns = [x.lower() for x in df.columns]

In [29]:
df

a         b         c
2000-01-01 -0.196995 -0.003352  0.444708
2000-01-02 -2.541531 -0.782247 -0.064333
2000-01-03  0.173113 -0.279730  1.465295
2000-01-04 -1.006320  0.893319  0.522331
2000-01-05 -0.255289  0.740723 -0.402440
2000-01-06 -1.917776 -0.406347  0.660013
2000-01-07  0.706273  0.703421 -1.135751
2000-01-08 -2.532381 -0.334399 -0.203312

In [33]:
ss = s.to_numpy()

In [34]:
ss

array([-0.13375523, -1.03406559, -1.27868732, -0.25237074, -1.85753406])

In [36]:
np.asarray(s)

array([-0.13375523, -1.03406559, -1.27868732, -0.25237074, -1.85753406])

In [37]:
ser = pd.Series(pd.date_range('2000', periods=2, tz="CET"))

In [38]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [39]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [40]:
df.to_numpy()

array([[-0.19699451, -0.00335161,  0.44470827],
       [-2.5415308 , -0.78224728, -0.0643335 ],
       [ 0.17311309, -0.27972953,  1.46529549],
       [-1.0063205 ,  0.89331854,  0.5223308 ],
       [-0.25528905,  0.74072346, -0.4024401 ],
       [-1.91777572, -0.40634654,  0.66001328],
       [ 0.70627302,  0.70342115, -1.13575119],
       [-2.53238133, -0.33439857, -0.20331176]])

In [41]:
df = pd.DataFrame({
   ....:     'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
   ....:     'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
   ....:     'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
   ....: 

In [42]:
df

one       two     three
a -0.402450 -2.053497       NaN
b -2.053713 -0.439188 -0.001390
c -1.559563 -0.511473  0.705063
d       NaN -0.246348 -0.351116

In [49]:
row = df.iloc[1]

In [45]:
column = df['two']

In [47]:
df.sub(row, axis='columns')

one       two     three
a  1.651263 -1.614309       NaN
b  0.000000  0.000000  0.000000
c  0.494150 -0.072284  0.706454
d       NaN  0.192840 -0.349726

In [54]:
df.sub(row, axis=1)

one       two     three
a  1.651263 -1.614309       NaN
b  0.000000  0.000000  0.000000
c  0.494150 -0.072284  0.706454
d       NaN  0.192840 -0.349726

In [55]:
df.sub(column, axis='index')

one  two     three
a  1.651047  0.0       NaN
b -1.614525  0.0  0.437798
c -1.048091  0.0  1.216536
d       NaN  0.0 -0.104768

In [56]:
df.sub(column, axis=0)

one  two     three
a  1.651047  0.0       NaN
b -1.614525  0.0  0.437798
c -1.048091  0.0  1.216536
d       NaN  0.0 -0.104768

In [57]:
dfmi = df.copy()

In [58]:
dfmi.index = pd.MultiIndex.from_tuples([(1, 'a'), (1, 'b'),
   ....:                                         (1, 'c'), (2, 'a')],
   ....:                                        names=['first', 'second'])
   ....: 

In [59]:
dfmi

one       two     three
first second                              
1     a      -0.402450 -2.053497       NaN
      b      -2.053713 -0.439188 -0.001390
      c      -1.559563 -0.511473  0.705063
2     a            NaN -0.246348 -0.351116

In [60]:
dfmi.sub(column, axis=0, level='second')

one       two     three
first second                              
1     a       1.651047  0.000000       NaN
      b      -1.614525  0.000000  0.437798
      c      -1.048091  0.000000  1.216536
2     a            NaN  1.807148  1.702381

In [61]:
s = pd.Series(np.arange(10))

In [62]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [72]:
div, rem = divmod(s, 3)

In [73]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int32

In [74]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

In [75]:
idx = pd.Index(np.arange(10))

In [76]:
div, rem = divmod(idx, 3)

In [77]:
df

one       two     three
a -0.402450 -2.053497       NaN
b -2.053713 -0.439188 -0.001390
c -1.559563 -0.511473  0.705063
d       NaN -0.246348 -0.351116

In [81]:
df2 = df.copy()

In [83]:
df.gt(df2)

one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [84]:
df2.ne(df)

one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

In [85]:
(df < 0).all()

one      False
two      False
three    False
dtype: bool

In [86]:
(df > 0).any()

one      False
two      False
three     True
dtype: bool

In [87]:
(df > 0).any().any()

True

In [88]:
df.empty

False

In [91]:
pd.DataFrame(columns=list('ABC')).empty

True

In [92]:
df + df == df * 2

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [93]:
(df + df == df * 2).all()

one      False
two       True
three    False
dtype: bool

In [94]:
(df + df).equals(df * 2)

True

In [103]:
df1 = pd.DataFrame({'col': ['foo', 0, np.nan]})
df1

col
0  foo
1    0
2  NaN

In [104]:
df2 = pd.DataFrame({'col': [np.nan, 0, 'foo']}, index=[2, 1, 0])
df2

col
2  NaN
1    0
0  foo

col
0  foo
1    0
2  NaN

In [105]:
df1.equals(df2)

False

In [106]:
df1.equals(df2.sort_index())

True

In [107]:
pd.Series(['foo', 'bar', 'baz']) == 'foo'

0     True
1    False
2    False
dtype: bool